package main

import (
	"fmt"

	code "google.golang.org/genproto/googleapis/rpc/code"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	"github.com/JasperLabs/grpcerrors"
)

var grpcCodeName = map[int32]string{
	0:  "OK",
	1:  "Canceled",
	2:  "Unknown",
	3:  "InvalidArgument",
	4:  "DeadlineExceeded",
	5:  "NotFound",
	6:  "AlreadyExists",
	7:  "PermissionDenied",
	8:  "ResourceExhausted",
	9:  "FailedPrecondition",
	10: "Aborted",
	11: "OutOfRange",
	12: "Unimplemented",
	13: "Internal",
	14: "Unavailable",
	15: "DataLoss",
	16: "Unauthenticated",
}

func generate(plugin *protogen.Plugin) error {
	// Track seen helper names per Go package to detect cross-file collisions.
	pkgSeen := make(map[protogen.GoImportPath]map[string]string)

	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		if !hasAnnotatedEnumValues(f) {
			continue
		}
		seen := pkgSeen[f.GoImportPath]
		if seen == nil {
			seen = make(map[string]string)
			pkgSeen[f.GoImportPath] = seen
		}
		generateFile(plugin, f, seen)
	}
	return nil
}

// allEnums returns all enums in a file, including those nested inside messages.
func allEnums(f *protogen.File) []*protogen.Enum {
	enums := append([]*protogen.Enum(nil), f.Enums...)
	var walkMessages func([]*protogen.Message)
	walkMessages = func(msgs []*protogen.Message) {
		for _, m := range msgs {
			enums = append(enums, m.Enums...)
			walkMessages(m.Messages)
		}
	}
	walkMessages(f.Messages)
	return enums
}

func hasAnnotatedEnumValues(f *protogen.File) bool {
	for _, enum := range allEnums(f) {
		for _, v := range enum.Values {
			if v.Desc.Number() == 0 {
				continue
			}
			if getGRPCCode(v) != nil {
				return true
			}
		}
	}
	return false
}

func generateFile(plugin *protogen.Plugin, f *protogen.File, seen map[string]string) {
	filename := f.GeneratedFilenamePrefix + "_errors.pb.go"
	g := plugin.NewGeneratedFile(filename, f.GoImportPath)

	g.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	codesPackage := protogen.GoImportPath("google.golang.org/grpc/codes")
	grpcErrorsPackage := protogen.GoImportPath("github.com/JasperLabs/grpcerrors")

	g.P("const _ = ", grpcErrorsPackage.Ident("SupportPackageIsVersion1"))
	g.P()

	domain := string(f.Desc.Package())

	for _, enum := range allEnums(f) {
		for _, v := range enum.Values {
			if v.Desc.Number() == 0 {
				continue
			}
			code := getGRPCCode(v)
			if code == nil {
				continue
			}

			codeName, ok := grpcCodeName[*code]
			if !ok {
				codeName = fmt.Sprintf("Code(%d)", *code)
			}

			reason := string(v.Desc.Name())
			pascal := toPascalCase(reason)

			if prev, dup := seen[pascal]; dup {
				g.P(
					"// ERROR: duplicate helper name \"",
					pascal,
					"\" from enum values \"",
					prev,
					"\" and \"",
					reason,
					"\"",
				)
				plugin.Error(fmt.Errorf(
					"duplicate helper name %q in %s: enum values %q and %q produce the same PascalCase name",
					pascal,
					f.Desc.Path(),
					prev,
					reason,
				))
				return
			}
			seen[pascal] = reason

			g.P("// ", reason, " -> codes.", codeName)
			g.P("func Error", pascal, "(msg ...string) *", grpcErrorsPackage.Ident("Error"), " {")
			g.P("	m := \"", reason, "\"")
			g.P("	if len(msg) > 0 {")
			g.P("		m = msg[0]")
			g.P("	}")
			g.P(
				"	return ",
				grpcErrorsPackage.Ident("New"),
				"(",
				codesPackage.Ident(codeName),
				", \"",
				reason,
				"\", \"",
				domain,
				"\", m)",
			)
			g.P("}")
			g.P()
			g.P("func Is", pascal, "(err error) bool {")
			g.P(
				"	return ",
				grpcErrorsPackage.Ident("MatchReasonDomain"),
				"(err, \"",
				reason,
				"\", \"",
				domain,
				"\")",
			)
			g.P("}")
			g.P()
		}
	}
}

func getGRPCCode(v *protogen.EnumValue) *int32 {
	opts := v.Desc.Options()
	if opts == nil {
		return nil
	}
	if !proto.HasExtension(opts, grpcerrors.E_GrpcCode) {
		return nil
	}
	c := int32(proto.GetExtension(opts, grpcerrors.E_GrpcCode).(code.Code))
	return &c
}
