// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: errors/errors.proto

package grpcerrors

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_errors_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*code.Code)(nil),
		Field:         50001,
		Name:          "errors.grpc_code",
		Tag:           "varint,50001,opt,name=grpc_code,enum=google.rpc.Code",
		Filename:      "errors/errors.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional google.rpc.Code grpc_code = 50001;
	E_GrpcCode = &file_errors_errors_proto_extTypes[0]
)

var File_errors_errors_proto protoreflect.FileDescriptor

const file_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x13errors/errors.proto\x12\x06errors\x1a google/protobuf/descriptor.proto\x1a\x15google/rpc/code.proto:R\n" +
	"\tgrpc_code\x12!.google.protobuf.EnumValueOptions\x18ц\x03 \x01(\x0e2\x10.google.rpc.CodeR\bgrpcCodeB-Z+github.com/JasperLabs/grpcerrors;grpcerrorsb\x06proto3"

var file_errors_errors_proto_goTypes = []any{
	(*descriptorpb.EnumValueOptions)(nil), // 0: google.protobuf.EnumValueOptions
	(code.Code)(0),                        // 1: google.rpc.Code
}
var file_errors_errors_proto_depIdxs = []int32{
	0, // 0: errors.grpc_code:extendee -> google.protobuf.EnumValueOptions
	1, // 1: errors.grpc_code:type_name -> google.rpc.Code
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_errors_proto_init() }
func file_errors_errors_proto_init() {
	if File_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_errors_proto_rawDesc), len(file_errors_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_errors_errors_proto_goTypes,
		DependencyIndexes: file_errors_errors_proto_depIdxs,
		ExtensionInfos:    file_errors_errors_proto_extTypes,
	}.Build()
	File_errors_errors_proto = out.File
	file_errors_errors_proto_goTypes = nil
	file_errors_errors_proto_depIdxs = nil
}
