// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package testv1

import (
	grpcerrors "github.com/JasperLabs/grpcerrors"
	codes "google.golang.org/grpc/codes"
)

const _ = grpcerrors.SupportPackageIsVersion1

// HOLDINGS_EXIST -> codes.FailedPrecondition
func ErrorHoldingsExist(msg ...string) *grpcerrors.Error {
	m := "HOLDINGS_EXIST"
	if len(msg) > 0 {
		m = msg[0]
	}
	return grpcerrors.New(codes.FailedPrecondition, "HOLDINGS_EXIST", "test.v1", m)
}

func IsHoldingsExist(err error) bool {
	return grpcerrors.MatchReasonDomain(err, "HOLDINGS_EXIST", "test.v1")
}

// FUND_NOT_FOUND -> codes.NotFound
func ErrorFundNotFound(msg ...string) *grpcerrors.Error {
	m := "FUND_NOT_FOUND"
	if len(msg) > 0 {
		m = msg[0]
	}
	return grpcerrors.New(codes.NotFound, "FUND_NOT_FOUND", "test.v1", m)
}

func IsFundNotFound(err error) bool {
	return grpcerrors.MatchReasonDomain(err, "FUND_NOT_FOUND", "test.v1")
}

// EMAIL_ALREADY_EXISTS -> codes.AlreadyExists
func ErrorEmailAlreadyExists(msg ...string) *grpcerrors.Error {
	m := "EMAIL_ALREADY_EXISTS"
	if len(msg) > 0 {
		m = msg[0]
	}
	return grpcerrors.New(codes.AlreadyExists, "EMAIL_ALREADY_EXISTS", "test.v1", m)
}

func IsEmailAlreadyExists(err error) bool {
	return grpcerrors.MatchReasonDomain(err, "EMAIL_ALREADY_EXISTS", "test.v1")
}

// DISTRIBUTION_ALREADY_CONFIRMED -> codes.FailedPrecondition
func ErrorDistributionAlreadyConfirmed(msg ...string) *grpcerrors.Error {
	m := "DISTRIBUTION_ALREADY_CONFIRMED"
	if len(msg) > 0 {
		m = msg[0]
	}
	return grpcerrors.New(codes.FailedPrecondition, "DISTRIBUTION_ALREADY_CONFIRMED", "test.v1", m)
}

func IsDistributionAlreadyConfirmed(err error) bool {
	return grpcerrors.MatchReasonDomain(err, "DISTRIBUTION_ALREADY_CONFIRMED", "test.v1")
}
